name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Build all Docker images
      working-directory: ${{ github.workspace }}/build
      run: |
        for f in *.Dockerfile; do
          echo "Building $f"
          docker build --tag "openspace-${f%.Dockerfile}" --file "$f" .
        done
